### ISSUE TITLE
Is there a way to customize the base map, map size, zoom level?

### ISSUE THREAD

**Issue by andyanderso** [AmericanAvalanche/avalanche.org-API-Client#1]
I would like to be able to customize the base map, map size, and zoom level. AKA set the map height to 600px and zoom level to 8 or something. Is this possible through the API?

**Comment by jimurl** [comment]
Hi Andy, W were checking that out too. Clark is working on a different base map ( colored instead of BW ). Perhaps there will be an option to set this in the http post data array.

I found that to fix the size of the map, I had to put it into a div of certain width and height. 

The zoom, we found, its set automatically, so that none of your regions are cut off. I had to tweak the height of ours because it was a hair to small to fit all the regions into. Once I made it slightly taller, it defaulted to the next zoom level up.

**Comment by andyanderso** [comment]
The `<div style="width:100%; height:600px;">` works great for the size. Thanks, Jim that is a nice simple solution! I would still like to set the zoom one level higher than it displays on our map to make our region take up all the space in the map window.

you can check out the 3 options on my dev site if you want to compare them:
[http://dev.sierraavalanchecenter.org](http://dev.sierraavalanchecenter.org)

**Comment by jimurl** [comment]
Yeah, I see what you mean. Try increasing the height a bit. I think whatever function auto zooms in or out, it likes to have some padding around the advisory area. Go big to find a height that will definitely work, then try dropping it down to the smallest height that will still give you the better zoom level.

**Comment by ccorey** [comment]
See docs for latest update. Client can now supply map height as well as desired zoom level.
